---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "nyse_app_service"
  name: "nyse-service"
spec:
  ports:
  - name: "port-1-nyse"
    port: 9090
    protocol: "TCP"
    targetPort: 9090
  selector:
    app: "nyse_app_service"
  type: "ClusterIP"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "nyse_app_service"
  name: "nyse-service-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "nyse_app_service"
  template:
    metadata:
      labels:
        app: "nyse_app_service"
    spec:
      containers:
      - image: "anjanas6/nyse:latest"
        lifecycle:
          preStop:
            exec:
              command:
              - "sleep"
              - "15"
        name: "nyse-service-deployment"
        ports:
        - containerPort: 9090
          name: "port-1-nyse"
          protocol: "TCP"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "200m"
      nodeSelector: {}
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  labels:
    app: "nyse_app_service"
  name: "nyse-service"
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: "nyse-service-deployment"
  targetCPUUtilizationPercentage: 50
