apiVersion: apps/v1
kind: Deployment
metadata:
  name: nyse-stage-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nyse-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: nyse-app
    spec:
      containers:
      - name: nyse-app
        image: anjanas6/nyse:latest
        ports:
        - containerPort: 9090
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: nyse-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 9090
  selector:
    app: nyse-app
