name: build and push docker image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ stage ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to workspace
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      
      - name: Build the Ballerina project
        uses: ballerina-platform/ballerina-action@master
        env:
          CI_BUILD: true
        with:
          args:
            build
      
      - name: Push to Docker hub
        run:  |
          docker push anjanas6/nyse:latest
