name: Create a k8s cluster on Google Cloud Platform

on:
  workflow_dispatch:

jobs:
  setup-cluster:
    name: Setup a Kubernetes cluster env
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

  # Authenticate via credentials JSON
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Execute
      run: |
        gcloud container clusters create nyse-cluster --num-nodes=3 --zone "us-central1-a" --async
